---
#
# Copyright (c) 2016, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
#- name: Remove archive
#  file: state=absent path={{ jdk8_tmp }}

- debug: var="jdk8_tmp"
- stat: path={{ jdk8_tmp }}
  register: jdktargz

- name: Download jdk8
  command: "wget -O {{ jdk8_tmp }} --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{ jdk8_url }} creates={{ jdk8_tmp }}"
  register: download
  when: jdktargz.stat.exists == False

- debug: var="download"
#- name: Check status
#  fail:
#    msg: ok
#  when:  has_error


# create the java home directory if not exist
- name: Create home folder
  file: state=directory path="{{ jdk8_home }}"
  register: jdk_create_folder_log

- name: Extract jdk8
  unarchive:
    copy: no
    src: "{{ jdk8_tmp }}"
    dest: "{{ jdk8_home }}"
    extra_opts: ['--strip=1']
  register: jdk8installed
- debug: var="jdk8installed"
  when: "{{ jdk8_log == '1' }}"

- name: Make Java available for system
  command: 'alternatives --install "/usr/bin/java" "java" "{{ jdk8_home }}/bin/java" 2000'
  become: true
  become_user: root

- name: Remove archive
  file: state=absent path={{ jdk8_tmp }}

- name: Update bashrc file
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    marker: "## {mark} jdk"
    block: |
      export JAVA_HOME={{ jdk8_home }}
      export PATH=$JAVA_HOME/bin:$PATH
    create: yes

